import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

type Issue={id:string;rule:string;status:string;category:string;severity:string;slide_id:string|null;element_ids:string[];message:string;repair:string;evidence:Record<string,unknown>};
type Box={x:number;y:number;w:number;h:number};
type Node={id:string;box:Box};
type Scene={version:number;slides:{id:string;title:string;nodes:Node[]}[]};
type Variant={version:number;scene:string;audit:string;pptx:string;html:string;pdf:string;previews:string[];issue_count:number};
type Job={id:string;state:string;stage:string;error:string;result:{variants?:Record<string,Variant>;elapsed_seconds?:number;deadline_met?:boolean}};
type Template={id:string;name:string;design:{prototypes:unknown[];fonts:string[];warnings:string[]}};
type Content={id:string;name:string;content:{claims:unknown[];datasets:unknown[]}};
const labels:Record<string,string>={A:'Последовательное изложение',B:'Визуальное объяснение',C:'Сравнения и показатели'};
const stages:Record<string,string>={queued:'В очереди',starting:'Запуск',loading:'Чтение материалов',planning:'Планирование содержания',layout_export_render:'Сборка и экспорт',contextual_audit:'Проверка содержания',finalizing:'Сохранение результата',ready:'Готово',awaiting_input:'Нужны сведения',failed:'Ошибка',cancelled:'Отменено'};
async function api<T>(url:string,init?:RequestInit):Promise<T>{const res=await fetch(url,init);if(!res.ok){const body=await res.json().catch(()=>({detail:'Ошибка сервера'}));throw new Error(String(body.detail))}return res.json()}
const fileURL=(job:string,path:string)=>`/api/jobs/${job}/file?path=${encodeURIComponent(path)}`;

function App(){
 const [templates,setTemplates]=useState<Template[]>([]),[contents,setContents]=useState<Content[]>([]);
 const [template,setTemplate]=useState(''),[content,setContent]=useState(''),[brief,setBrief]=useState(''),[count,setCount]=useState(12),[purpose,setPurpose]=useState('project'),[images,setImages]=useState(false);
 const [job,setJob]=useState<Job|null>(null),[variant,setVariant]=useState('A'),[scene,setScene]=useState<Scene|null>(null),[issues,setIssues]=useState<Issue[]>([]),[selected,setSelected]=useState<Set<string>>(new Set()),[slide,setSlide]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[health,setHealth]=useState<{model_configured:boolean;image_model_configured:boolean;renderer_available:boolean}|null>(null);
 async function refresh(){const [ts,cs]=await Promise.all([api<Template[]>('/api/templates'),api<Content[]>('/api/content')]);setTemplates(ts);setContents(cs);setTemplate(prev=>prev||ts[0]?.id||'');setContent(prev=>prev||cs[0]?.id||'')}
 useEffect(()=>{refresh().catch(e=>setError(e.message));api<typeof health>('/api/health').then(setHealth).catch(e=>setError(e.message));const id=localStorage.getItem('vktech-job');if(id)api<Job>('/api/jobs/'+id).then(setJob).catch(()=>localStorage.removeItem('vktech-job'))},[]);
 useEffect(()=>{if(!job||!['queued','running'].includes(job.state))return;const timer=setInterval(()=>api<Job>('/api/jobs/'+job.id).then(setJob).catch(e=>setError(e.message)),1500);return()=>clearInterval(timer)},[job?.id,job?.state]);
 useEffect(()=>{if(job)localStorage.setItem('vktech-job',job.id)},[job?.id]);
 useEffect(()=>{let active=true;setScene(null);setIssues([]);setSelected(new Set());const v=job?.result.variants?.[variant];if(!job||job.state!=='ready'||!v)return;Promise.all([api<Scene>(fileURL(job.id,v.scene)),api<{issues:Issue[]}>(fileURL(job.id,v.audit))]).then(([s,a])=>{if(active){setScene(s);setIssues(a.issues);setSlide(0)}}).catch(e=>setError(e.message));return()=>{active=false}},[job?.id,job?.state,variant]);
 async function upload(kind:'templates'|'content',file:File){setBusy(true);setError('');try{const body=new FormData();body.append('file',file);const result=await api<{id:string}>('/api/'+kind,{method:'POST',body});await refresh();if(kind==='templates')setTemplate(result.id);else setContent(result.id)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function start(){setBusy(true);setError('');try{const r=await api<{id:string}>('/api/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({template_id:template,content_id:content,brief,purpose,slide_count:count,generate_images:images})});setJob(await api<Job>('/api/jobs/'+r.id))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function repair(){if(!job||!scene)return;setBusy(true);setError('');try{const r=await api<{id:string}>(`/api/jobs/${job.id}/repair`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({variant,expected_version:scene.version,issue_ids:[...selected],idempotency_key:crypto.randomUUID()})});setJob(await api<Job>('/api/jobs/'+r.id))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const current=templates.find(t=>t.id===template),v=job?.result.variants?.[variant],currentSlide=scene?.slides[slide],failures=issues.filter(i=>i.status==='fail'&&(i.slide_id===currentSlide?.id||!i.slide_id)),unknowns=issues.filter(i=>i.status==='unknown');
 return <div className="app"><header><div className="logo">VK</div><div><b>Презентации</b><span>Цифровой дизайнер · VK Tech</span></div><div className="header-note">Один набор фактов. Три способа рассказать.</div></header>
 <main><aside className="setup"><div className="eyebrow">НОВАЯ ПРЕЗЕНТАЦИЯ</div><h1>От материалов<br/>к готовым слайдам</h1><p className="muted">Загрузите фирменный шаблон и исходные материалы. Сервис соберёт варианты и покажет, что стоит исправить.</p>
 <label>Шаблон PPTX<select value={template} onChange={e=>setTemplate(e.target.value)}><option value="">Выберите шаблон</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className="upload">＋ Загрузить шаблон<input type="file" accept=".pptx" disabled={busy} onChange={e=>{if(e.target.files?.[0])upload('templates',e.target.files[0]);e.target.value=''}}/></label>
 {current&&<div className="template-info">{current.design.prototypes.length} композиций · {current.design.fonts.join(', ')}{current.design.warnings.map(w=><p key={w} className="notice">{w}</p>)}</div>}
 <label>Исходные материалы<select value={content} onChange={e=>setContent(e.target.value)}><option value="">Выберите материалы</option>{contents.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="upload">＋ Загрузить материалы<input type="file" accept=".json,.txt,.md,.pptx,.pdf,.csv" disabled={busy} onChange={e=>{if(e.target.files?.[0])upload('content',e.target.files[0]);e.target.value=''}}/></label>
 <label>Что должна объяснить презентация?<textarea value={brief} onChange={e=>setBrief(e.target.value)} placeholder="Например: объяснить пользу продукта руководителям и предложить следующий шаг" rows={4}/></label>
 <div className="row"><label>Назначение<select value={purpose} onChange={e=>setPurpose(e.target.value)}><option value="project">Проект</option><option value="product">Продукт</option><option value="feature">Новая функция</option><option value="initiative">Инициатива</option></select></label><label>Слайды<input type="number" min={1} max={50} value={count} onChange={e=>setCount(Number(e.target.value))}/></label></div>
 <label className="checkbox"><input type="checkbox" checked={images} disabled={!health?.image_model_configured} onChange={e=>setImages(e.target.checked)}/>Создать новую иллюстрацию</label>
 <button className="primary" onClick={start} disabled={busy||!template||!content||!brief.trim()||['queued','running'].includes(job?.state||'')}>Создать три варианта</button>
 {health&&!health.model_configured&&<p className="notice">Для генерации нужно настроить подключение к модели.</p>}{health&&!health.image_model_configured&&<p className="notice">Новые иллюстрации отключены: генератор изображений не настроен. Картинки из исходных материалов доступны.</p>}{health&&!health.renderer_available&&<p className="notice">Серверу нужен LibreOffice для PDF и превью.</p>}
 </aside><section className="workspace">{error&&<div role="alert" className="error">{error}<button onClick={()=>setError('')}>×</button></div>}
 {!job&&<div className="empty"><div className="empty-card"><div className="mock-title"/><div className="mock-line"/><div className="mock-line short"/><div className="mock-bars"><i/><i/><i/></div></div><h2>Здесь появятся ваши варианты</h2><p>Выберите композицию, просмотрите аудит<br/>и скачайте готовую презентацию.</p></div>}
 {job&&<><div className="status"><span className={'dot '+job.state}/><b>{stages[job.stage]||job.stage}</b>{job.state==='ready'&&<span>{job.result.elapsed_seconds} с · {job.result.deadline_met?'в пределах 5 минут':'лимит 5 минут превышен'}</span>}{['queued','running'].includes(job.state)&&<button onClick={()=>api<Job>(`/api/jobs/${job.id}/cancel`,{method:'POST'}).then(setJob).catch(e=>setError(e.message))}>Отменить</button>}</div>
 {job.error&&<div className="error">{job.error}</div>}{['failed','awaiting_input'].includes(job.state)&&<button onClick={()=>api<Job>(`/api/jobs/${job.id}/retry`,{method:'POST'}).then(setJob).catch(e=>setError(e.message))}>Повторить после устранения причины</button>}
 {job.state==='ready'&&<><nav className="variants">{Object.entries(labels).map(([id,label])=><button key={id} className={variant===id?'active':''} onClick={()=>setVariant(id)}><b>{id}</b>{label}<span>{job.result.variants?.[id]?.issue_count??0} замечаний</span></button>)}</nav>
 {v&&<div className="exports"><span>Версия {v.version}</span>{(['pptx','pdf','html'] as const).map(format=><a key={format} href={fileURL(job.id,v[format])} download={`presentation-${variant}.${format}`}>{format.toUpperCase()} ↓</a>)}</div>}
 {v&&currentSlide&&<div className="review"><div className="viewer"><div className="slide-preview"><img src={fileURL(job.id,v.previews[slide])} alt={currentSlide.title}/>{failures.flatMap(i=>i.element_ids.map(id=>{const n=currentSlide.nodes.find(n=>n.id===id);return n?<div key={i.id+id} className={'highlight '+(selected.has(i.id)?'selected':'')} title={i.message} style={{left:n.box.x*100+'%',top:n.box.y*100+'%',width:n.box.w*100+'%',height:n.box.h*100+'%'}}/>:null}))}</div><div className="pagination"><button disabled={slide===0} onClick={()=>setSlide(slide-1)}>←</button><span>{slide+1} / {scene?.slides.length} · {currentSlide.title}</span><button disabled={slide+1===(scene?.slides.length||0)} onClick={()=>setSlide(slide+1)}>→</button></div><div className="thumbs">{v.previews.map((p,i)=><button key={p} className={slide===i?'active':''} onClick={()=>setSlide(i)}><img src={fileURL(job.id,p)} alt={`Слайд ${i+1}`}/><span>{i+1}</span></button>)}</div></div>
 <aside className="audit"><div className="eyebrow">АУДИТ</div><h2>Проверка слайда</h2><p className="muted">Отметьте замечания, которые нужно исправить.</p>{failures.length===0&&<p className="good">Нарушений не найдено.</p>}{failures.map(i=><label key={i.id} className="issue"><input type="checkbox" checked={selected.has(i.id)} disabled={i.repair==='none'} onChange={e=>setSelected(prev=>{const next=new Set(prev);e.target.checked?next.add(i.id):next.delete(i.id);return next})}/><div><small>{i.rule} · {i.category==='contextual'?'Смысл':'Объекты'}</small><p>{i.message}</p>{i.repair==='none'&&<span>Требует ручного решения</span>}</div></label>)}<button className="primary" disabled={busy||selected.size===0} onClick={repair}>Исправить выбранное ({selected.size})</button>{unknowns.length>0&&<details><summary>Не проверено: {unknowns.length}</summary>{unknowns.map(i=><p key={i.id}>{i.rule}: {i.message}</p>)}</details>}</aside></div>}</>}
 </>}
 </section></main><footer>Оформление из вашего шаблона · содержание из ваших материалов</footer></div>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
